[package]
name = "rinput"
version = "0.1.0"
edition = "2021"

description = "一个简单的 rust 输入库"
license = "GPL3"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
