[package]
name = "rinput"
version = "0.1.0"
edition = "2021"

description = "一个简单的 rust 输入库"
license-file = "LICENSE"
repository = "https://github.com/tbontb-iaq/rinput"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
